### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'rec_loss'

### ISSUE THREAD

**Issue by Wonder1905** [yossigandelsman/test_time_training_mae#4]
Hi, I'm trying to run "main_test_time_training.py" , I'm getting the following error:
`AttributeError: 'Namespace' object has no attribute 'rec_loss'`

I'm running the script with the following arguments:
`Namespace(accum_iter=1, base_lr=0.01, batch_size=128, blr=0.01, classifier_depth=12, data_path='/workspace/imagenet_c', device='cuda', dist_on_itp=False, dist_url='file://.../01', distributed=False, finetune_mode='encoder', head_type='vit_head', input_size=224, load_loss_scalar=False, local_rank=-1, log_dir='./output_dir', lr=0.005, mask_ratio=0.75, model='mae_vit_large_patch16', norm_pix_loss=True, num_workers=10, optimizer_momentum=0.9, optimizer_type='sgd', output_dir='./output', pin_mem=False, print_freq=50, resume_finetune='checkpoints/prob_lr1e-3_wd.2_blk12_ep20.pth', resume_model='checkpoints/mae_pretrain_vit_large_full.pth', seed=0, single_crop=True, steps_per_example=20, stored_latents='', verbose=False, weight_decay=0.05, world_size=1)`
Full log:
```
  File "/workspace/test_time_training_mae/main_test_time_training.py", line 228, in <module>
    main(args)
  File "/workspace/test_time_training_mae/main_test_time_training.py", line 208, in main
    test_stats = train_on_test(
  File "/workspace/test_time_training_mae/engine_test_time.py", line 127, in train_on_test
    mask_ratio = args.mask_ratio if args.rec_loss else 0
AttributeError: 'Namespace' object has no attribute 'rec_loss'
```

I'll be happy for your help

**Comment by yossigandelsman** [comment]
Just pushed a bugfix. Please let me know if it works for you

**Comment by Wonder1905** [comment]
Yes it helped, thanks!
If I may another small Q, I'm running test_without_adaptation.py, with the following arguments:
`--data_path /workspace/imagenet_c --model mae_vit_large_patch16 --input_size 224 --classifier_depth 12 --head_type vit_head --output_dir ./output --resume_model checkpoints/mae_pretrain_vit_large_full.pth --resume_finetune checkpoints/prob_lr1e-3_wd.2_blk12_ep20.pth .
I have both of the checkpoints, and when debugging the checkpoint loading seems to be prefect, Further , when looking at the logits it is seems that the DNN not random. But still when I'm running the above script the accuracy is very close to 0, any idea why?

**Comment by yossigandelsman** [comment]
The data_path should be a specific subcategory of imagenet_c, so it should point to imagenet_c/corruption_name/corruption_level. Is that the case for you? can you please share on what of the corruptions+corruption_levels you get a very low accuracy?

**Comment by Wonder1905** [comment]
My path was incorrect, sorry for that.
Thanks for your help!

**Comment by Wonder1905** [comment]
One more question about the evaluation of ImagenetC , in the paper you showed results only on few classes, why is that? why there is no mean score on all the classes? is that what accepted on this dataset? (test_without_adaptation.py has no per class granularity)
Thanks a lot for your help and patience!

**Comment by yossigandelsman** [comment]
We evaluated our model on the standard corruption classes of imagenet-c (excluding the "extra" category, which is usually not presented). test_without_adaptation should be run separately on each type of corruption and level of corruption to achieve what you want. it can not be run on all the corruptions together, but a simple bash script can do the trick. Please see the README for more info.
