### ISSUE TITLE
A few questions about implementation

### ISSUE THREAD

**Issue by Wang-pengfei** [yossigandelsman/test_time_training_mae#5]
Thanks for sharing the code!  I have a few questions for you. 

First, when performing test-time training, it seems that the implementation is iterating once for each of the 20 different samples, rather than iterating 20 times for each sample as stated in the paper.   [code link](https://github.com/yossigandelsman/test_time_training_mae/blob/82b93952c7fe2a3c4e7c4410d463b8164c00d4d9/engine_test_time.py#L122)

Second, if I'm not mistaken when performing test-time training, it seems that the samples for training are different from the samples for testing. Is this reasonable?

**Comment by yossigandelsman** [comment]
Notice that the dataset is not the regular Imagenet. every `next` returns the same image: 
[code link](https://github.com/yossigandelsman/test_time_training_mae/blob/82b93952c7fe2a3c4e7c4410d463b8164c00d4d9/data/tt_image_folder.py#L30)

**Comment by Wang-pengfei** [comment]
Thank you for your reply. I have another question, is the number of samples in the test time training 1 or 128? [code link](https://github.com/yossigandelsman/test_time_training_mae/blob/82b93952c7fe2a3c4e7c4410d463b8164c00d4d9/engine_test_time.py#L127)
