### ISSUE TITLE
question about implementation of TTT-MAE

### ISSUE THREAD

**Issue by jimmylihui** [yossigandelsman/test_time_training_mae#8]
In the paper, the test time training should use a test dataset to train, but in the implementation, the test time training uses the training dataset to train, why is that?

**Comment by yossigandelsman** [comment]
There is a pretraining stage that runs on the training data. Then the test-time training is done on each individual test sample.

**Comment by tian1327** [comment]
If TTT is done on each individual test sample, why is the batchsize for TTT=128? 

What is the difference between the training data and testing data in the code for TTT?

Thank you!
