### ISSUE TITLE
Question about Pretrain

### ISSUE THREAD

**Issue by Maxxxx-he** [yossigandelsman/test_time_training_mae#9]
Thanks for your sharing.
1. In the pretrain epoch 0, the pred is None in line 80 of engine_pretrain.py since Target is None in line 61 which lead to line 80 accurancy function error. 
2. In pretrain epoch 0, module.pos_embed, module.decoder_pos_embed, module.head.weight, module.head.bias with gradient None. Why is that and how to solve?

**Comment by warpcut** [comment]
Hi @Maxxxx-he , how did you solve this?
